# Generated by Django 5.0.7 on 2024-09-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rents", "0002_rename_rent_rental_alter_rental_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="rental_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
