# Generated by Django 5.0.7 on 2024-09-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rents", "0003_rental_rental_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="rental_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
