# Generated by Django 5.0.7 on 2024-10-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rents", "0004_alter_rental_rental_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="rental_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
