# Generated by Django 5.0.7 on 2024-08-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('S', 'Satisfactory')], max_length=12)),
                ('type', models.CharField(choices=[('A', 'Adult'), ('J', 'Junior'), ('K', 'Kids')], max_length=1)),
                ('gear_count', models.IntegerField()),
                ('frame_type', models.CharField(choices=[('U', 'Urban'), ('M', 'Mountain'), ('R', 'Road'), ('T', 'Touring')], max_length=8)),
                ('wheel_size', models.IntegerField()),
                ('colour', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bicycles/')),
                ('rental_cost_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rental_cost_day', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rented', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'bicycle',
                'verbose_name_plural': 'bicycles',
            },
        ),
    ]
