# Generated by Django 5.0.7 on 2024-09-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bicycle",
            old_name="rented",
            new_name="is_rented",
        ),
    ]
